### ISSUE TITLE
Rewrite playlist support

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#124]
- [x] Save playlists to m3u files in Music folder instead of in database
- [x] Song in playlist should be independent of the collection. Fetch track data from the files on the fly to make them playable.
- [x] Add option "Add to playlist -> New playlist" (see #122)
- [x] Removing songs from playlists should not cause a complete reload (see #50) 
- [x] Add currently playing song to a playlist (see #25)
- [x] Rearrange songs in playlists (see #21) 
- [x] Add songs from one playlist to another (see #19)
- [x] Drag and drop of files from Windows Explorer into playlists
- [x] Drag and drop of playlist files (m3u, zpl,..) into playlists column should add the playlist
- [x] Drag and drop of playlist files (m3u, zpl,..) into tracks column should add the files to the selected playlist
- [x] These features might require separation of rating and love to a separate database table. As those features should also work for file which are only added by playlist.
- [x] m3u files which are dropped in the My Music\Dopamine\Playlists folder, should be picked up automatically
