### ISSUE TITLE
TODO for Dopamine 2.0 Preview 2

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#828]
- [x] CTRL+F should activate the search field https://github.com/digimezzo/Dopamine/issues/733
- [x] Fix information screen keyboard button color
- [x] Fix https://github.com/digimezzo/Dopamine/issues/803 (Hamburger menu animation not working when OOBE first shown)
- [x] Add back button when in the Settings and Information sections
- [x] Implement #424 Implement smart playlists
- [x] Implement https://github.com/digimezzo/Dopamine/issues/484 (Collection - "Folder" Section)
