### ISSUE TITLE
Incorrectly tagged albums show up as "Unknown artist"

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#910]
In Artists view .. Select Artist, Albums show for that artist, but under the Album name is shows Unknown Artist. I assume this is something to do with Artist/Album Artist? If the Artist field is populated and the Album Artist is blank, could we show the Artist field instead of Unknown?

**TODO for those that don't want to tag correctly:**

- [ ] Add a property "PossiblyFakeAlbumArtist" to AlbumViewModel
- [ ] Add a property "PossiblyFakeAlbumArtist" to TrackViewModel
- [ ] Use the "PossiblyFake..." properties for display in the UI. Don't change the indexing logic. That should still solely rely on the real album artist tag.

**Be very careful with sorting: it should probably sort on fake album artists**

**Comment by Eqnesto** [comment]
![bug](https://user-images.githubusercontent.com/16270563/48967336-17126280-efb5-11e8-9581-06ec82c67a2b.png)
![bug 2](https://user-images.githubusercontent.com/16270563/48967349-4a54f180-efb5-11e8-8c12-c72d38e8366b.png)

Please use Artist metadata instead of Album Artist. Thanks!
